/* Generated by re2c 3.1 */
#line 1 "block_scanner.re"
// @file block_scanner.re
// @brief re2c source for the AsciiDoc block-level line scanner.
//
// This file is compiled by re2c to produce block_scanner_gen.h.
// Command: re2c --no-generation-date -W -o block_scanner_gen.h block_scanner.re
//
// A pre-generated copy is committed as block_scanner_gen.h so that re2c is
// NOT required at build time.  When USE_RE2C=ON and re2c is found by CMake,
// the file is regenerated automatically.
// Design notes:
// -------------
// * The input is a single AsciiDoc line passed as (const char*, size_t len)
//   where line[len] == '\0'.  std::string::c_str()/size() is always correct.
// * Rules are ordered so more specific patterns appear first; re2c uses the
//   FIRST matching rule on ties (same length).
// * Comment lines ("//...") appear before description-list rules, providing
//   the same guard as the (?!//[^/]) negative lookahead in the PCRE2 pattern.
// * Thematic-break patterns that require backreferences (e.g., the "---" /
//   "* * *" / "_ _ _" family using ([-*_])( *)\1\2\1) are NOT handled here.
//   The wrapper in block_scanner.c detects them with a fast C function BEFORE
//   calling aq_classify_line().  This keeps the re2c DFA free of patterns
//   that are inherently non-regular.
// * Delimited-block fence rules cover 2 characters ("--") through 4+.
//   The three-character fence ("---", "...") is intentionally absent so that
//   it falls through to the AQ_BT_TEXT default, allowing the wrapper's
//   thematic-break pre-check to reclaim it.

#include "block_scanner.h"
#include <stddef.h>

/* ── Internal DFA classifier ─────────────────────────────────────────────────
 *
 * Called by aq_scan_block_line() AFTER the thematic-break pre-check.
 * Returns the broad token type; capture extraction is done by the wrapper.
 */
static AqBlockToken aq_classify_line(const char *p, size_t len)
{
    const char *pe       = p + len;  /* NUL sentinel is at *pe  */
    const char *YYMARKER = p;        /* backtrack marker         */
    (void)YYMARKER;
    (void)pe;  /* YYLIMIT alias; unused when yyfill:enable = 0 */

    
#line 47 "block_scanner_gen.h"
{
	unsigned char yych;
	yych = *p;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case ' ': goto yy4;
		case '*': goto yy5;
		case '+': goto yy6;
		case '-': goto yy7;
		case '.': goto yy8;
		case '/': goto yy9;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy10;
		case ':': goto yy11;
		case ';': goto yy12;
		case '<': goto yy13;
		case '=': goto yy14;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'W':
		case 'Y':
		case 'Z':
		case 'b':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'w':
		case 'y':
		case 'z': goto yy15;
		case 'I':
		case 'V':
		case 'X':
		case 'x': goto yy16;
		case '[': goto yy17;
		case '_': goto yy18;
		case 'a': goto yy19;
		case 'e': goto yy20;
		case 'i': goto yy21;
		case 'v': goto yy22;
		case '~': goto yy23;
		default: goto yy2;
	}
yy1:
	++p;
#line 60 "block_scanner.re"
	{ return AQ_BT_BLANK; }
#line 135 "block_scanner_gen.h"
yy2:
	yych = *(YYMARKER = ++p);
	if (yych >= 0x01) goto yy25;
yy3:
#line 179 "block_scanner.re"
	{ return AQ_BT_TEXT; }
#line 142 "block_scanner_gen.h"
yy4:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00:
		case '\t':
		case ' ':
		case '*':
		case '-':
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy30;
		default: goto yy3;
	}
yy5:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy38;
		default: goto yy25;
	}
yy6:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '+': goto yy39;
		default: goto yy25;
	}
yy7:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '\t':
		case ' ': goto yy40;
		case '-': goto yy41;
		default: goto yy25;
	}
yy8:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ' ': goto yy43;
		case '.': goto yy44;
		default: goto yy42;
	}
yy9:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '/': goto yy45;
		default: goto yy25;
	}
yy10:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '.': goto yy46;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy47;
		default: goto yy25;
	}
yy11:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '!': goto yy48;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy49;
		case ':': goto yy50;
		default: goto yy25;
	}
yy12:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ';': goto yy51;
		default: goto yy25;
	}
yy13:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '.': goto yy52;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy53;
		case '<': goto yy54;
		default: goto yy25;
	}
yy14:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '\t':
		case ' ': goto yy55;
		case '=': goto yy56;
		default: goto yy25;
	}
yy15:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ')': goto yy57;
		case '.': goto yy58;
		default: goto yy25;
	}
yy16:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ')': goto yy59;
		case '.': goto yy58;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy60;
		default: goto yy25;
	}
yy17:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '[': goto yy65;
		case ']': goto yy24;
		default: goto yy62;
	}
yy18:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '_': goto yy66;
		default: goto yy25;
	}
yy19:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ')': goto yy57;
		case '.': goto yy58;
		case 'u': goto yy67;
		default: goto yy25;
	}
yy20:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ')': goto yy57;
		case '.': goto yy58;
		case 'n': goto yy68;
		default: goto yy25;
	}
yy21:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ')': goto yy59;
		case '.': goto yy58;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy60;
		case 'f': goto yy69;
		case 'm': goto yy70;
		case 'n': goto yy71;
		default: goto yy25;
	}
yy22:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ')': goto yy59;
		case '.': goto yy58;
		case 'I':
		case 'V':
		case 'X':
		case 'v':
		case 'x': goto yy60;
		case 'i': goto yy72;
		default: goto yy25;
	}
yy23:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '~': goto yy73;
		default: goto yy25;
	}
yy24:
	yych = *++p;
yy25:
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy26:
	p = YYMARKER;
	goto yy3;
yy27:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy74;
		case ';': goto yy28;
		default: goto yy24;
	}
yy28:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy27;
		case ';': goto yy75;
		default: goto yy24;
	}
yy29:
	yych = *++p;
yy30:
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case ' ': goto yy29;
		case '*': goto yy31;
		case '-': goto yy32;
		case '.': goto yy33;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy34;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'W':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'w':
		case 'y':
		case 'z': goto yy35;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy36;
		default: goto yy26;
	}
yy31:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy76;
		default: goto yy26;
	}
yy32:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy40;
		default: goto yy26;
	}
yy33:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy77;
		default: goto yy26;
	}
yy34:
	yych = *++p;
	switch (yych) {
		case '.': goto yy78;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy34;
		default: goto yy26;
	}
yy35:
	yych = *++p;
	switch (yych) {
		case ')': goto yy79;
		case '.': goto yy80;
		default: goto yy26;
	}
yy36:
	yych = *++p;
	switch (yych) {
		case '.': goto yy80;
		default: goto yy83;
	}
yy37:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy37;
		default: goto yy84;
	}
yy38:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy85;
		default: goto yy25;
	}
yy39:
	yych = *++p;
	switch (yych) {
		case '+': goto yy86;
		default: goto yy25;
	}
yy40:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy40;
		default: goto yy87;
	}
yy41:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy88;
		case '-': goto yy89;
		default: goto yy25;
	}
yy42:
	yych = *++p;
	if (yych <= 0x00) goto yy90;
	goto yy42;
yy43:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy43;
		default: goto yy91;
	}
yy44:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy92;
		default: goto yy25;
	}
yy45:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy93;
		case '/': goto yy95;
		default: goto yy94;
	}
yy46:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy96;
		default: goto yy25;
	}
yy47:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '.': goto yy46;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy47;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy48:
	yych = *++p;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy49;
		default: goto yy25;
	}
yy49:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ' ':
		case '\'':
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy49;
		case ':': goto yy97;
		case ';': goto yy28;
		default: goto yy24;
	}
yy50:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy98;
		case '\t':
		case ' ': goto yy99;
		case ':': goto yy100;
		default: goto yy25;
	}
yy51:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy101;
		case '\t':
		case ' ': goto yy102;
		case ';': goto yy75;
		default: goto yy25;
	}
yy52:
	yych = *++p;
	switch (yych) {
		case '>': goto yy103;
		default: goto yy25;
	}
yy53:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy53;
		case ':': goto yy27;
		case ';': goto yy28;
		case '>': goto yy103;
		default: goto yy24;
	}
yy54:
	yych = *++p;
	switch (yych) {
		case '<': goto yy104;
		default: goto yy25;
	}
yy55:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy55;
		default: goto yy105;
	}
yy56:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy55;
		case '=': goto yy106;
		default: goto yy25;
	}
yy57:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy107;
		default: goto yy25;
	}
yy58:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy108;
		default: goto yy25;
	}
yy59:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy109;
		default: goto yy25;
	}
yy60:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ')': goto yy59;
		case ':': goto yy27;
		case ';': goto yy28;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy60;
		default: goto yy24;
	}
yy61:
	yych = *++p;
yy62:
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy63;
		case ';': goto yy64;
		case ']': goto yy110;
		default: goto yy61;
	}
yy63:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy111;
		case ';': goto yy64;
		case ']': goto yy110;
		default: goto yy61;
	}
yy64:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy63;
		case ';': goto yy112;
		case ']': goto yy110;
		default: goto yy61;
	}
yy65:
	yych = *++p;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy113;
		default: goto yy25;
	}
yy66:
	yych = *++p;
	switch (yych) {
		case '_': goto yy114;
		default: goto yy25;
	}
yy67:
	yych = *++p;
	switch (yych) {
		case 'd': goto yy115;
		default: goto yy25;
	}
yy68:
	yych = *++p;
	switch (yych) {
		case 'd': goto yy116;
		default: goto yy25;
	}
yy69:
	yych = *++p;
	switch (yych) {
		case 'd': goto yy117;
		case 'e': goto yy118;
		case 'n': goto yy119;
		default: goto yy25;
	}
yy70:
	yych = *++p;
	switch (yych) {
		case 'a': goto yy120;
		default: goto yy25;
	}
yy71:
	yych = *++p;
	switch (yych) {
		case 'c': goto yy121;
		default: goto yy25;
	}
yy72:
	yych = *++p;
	switch (yych) {
		case ')': goto yy59;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy60;
		case 'd': goto yy122;
		default: goto yy25;
	}
yy73:
	yych = *++p;
	switch (yych) {
		case '~': goto yy123;
		default: goto yy25;
	}
yy74:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy125;
		case ':': goto yy74;
		case ';': goto yy28;
		default: goto yy24;
	}
yy75:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy127;
		case ':': goto yy27;
		case ';': goto yy75;
		default: goto yy24;
	}
yy76:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy128;
		default: goto yy26;
	}
yy77:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy129;
		default: goto yy26;
	}
yy78:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy96;
		default: goto yy26;
	}
yy79:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy107;
		default: goto yy26;
	}
yy80:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy108;
		default: goto yy26;
	}
yy81:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy109;
		default: goto yy26;
	}
yy82:
	yych = *++p;
yy83:
	switch (yych) {
		case ')': goto yy81;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy82;
		default: goto yy26;
	}
yy84:
	yych = *++p;
	if (yych <= 0x00) goto yy130;
	goto yy84;
yy85:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy131;
		default: goto yy25;
	}
yy86:
	yych = *++p;
	switch (yych) {
		case '+': goto yy132;
		default: goto yy25;
	}
yy87:
	yych = *++p;
	if (yych <= 0x00) goto yy133;
	goto yy87;
yy88:
	++p;
#line 104 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1214 "block_scanner_gen.h"
yy89:
	yych = *++p;
	switch (yych) {
		case '-': goto yy134;
		default: goto yy25;
	}
yy90:
	++p;
#line 137 "block_scanner.re"
	{ return AQ_BT_BLOCK_TITLE; }
#line 1225 "block_scanner_gen.h"
yy91:
	yych = *++p;
	if (yych <= 0x00) goto yy135;
	goto yy91;
yy92:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy136;
		default: goto yy25;
	}
yy93:
	++p;
#line 72 "block_scanner.re"
	{ return AQ_BT_COMMENT; }
#line 1242 "block_scanner_gen.h"
yy94:
	yych = *++p;
	if (yych <= 0x00) goto yy137;
	goto yy94;
yy95:
	yych = *++p;
	switch (yych) {
		case '/': goto yy138;
		default: goto yy25;
	}
yy96:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy96;
		default: goto yy139;
	}
yy97:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy140;
		case '\t':
		case ' ': goto yy141;
		case ':': goto yy74;
		default: goto yy25;
	}
yy98:
	++p;
#line 171 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1274 "block_scanner_gen.h"
yy99:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy142;
yy100:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy98;
		case '\t':
		case ' ': goto yy99;
		case ':': goto yy143;
		default: goto yy25;
	}
yy101:
	++p;
#line 173 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1292 "block_scanner_gen.h"
yy102:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy144;
yy103:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy145;
		default: goto yy25;
	}
yy104:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy146;
		case ':': goto yy27;
		case ';': goto yy28;
		case '<': goto yy104;
		default: goto yy24;
	}
yy105:
	yych = *++p;
	if (yych <= 0x00) goto yy147;
	goto yy105;
yy106:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy55;
		case '=': goto yy148;
		default: goto yy25;
	}
yy107:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy107;
		default: goto yy149;
	}
yy108:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy108;
		default: goto yy150;
	}
yy109:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy109;
		default: goto yy151;
	}
yy110:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy152;
		case ':': goto yy63;
		case ';': goto yy64;
		case ']': goto yy110;
		default: goto yy61;
	}
yy111:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy153;
		case ':': goto yy111;
		case ';': goto yy64;
		case ']': goto yy110;
		default: goto yy61;
	}
yy112:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy154;
		case ':': goto yy63;
		case ';': goto yy112;
		case ']': goto yy110;
		default: goto yy61;
	}
yy113:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy155;
		case ';': goto yy156;
		case ']': goto yy157;
		default: goto yy113;
	}
yy114:
	yych = *++p;
	switch (yych) {
		case '_': goto yy158;
		default: goto yy25;
	}
yy115:
	yych = *++p;
	switch (yych) {
		case 'i': goto yy159;
		default: goto yy25;
	}
yy116:
	yych = *++p;
	switch (yych) {
		case 'i': goto yy160;
		default: goto yy25;
	}
yy117:
	yych = *++p;
	switch (yych) {
		case 'e': goto yy161;
		default: goto yy25;
	}
yy118:
	yych = *++p;
	switch (yych) {
		case 'v': goto yy162;
		default: goto yy25;
	}
yy119:
	yych = *++p;
	switch (yych) {
		case 'd': goto yy163;
		default: goto yy25;
	}
yy120:
	yych = *++p;
	switch (yych) {
		case 'g': goto yy164;
		default: goto yy25;
	}
yy121:
	yych = *++p;
	switch (yych) {
		case 'l': goto yy165;
		default: goto yy25;
	}
yy122:
	yych = *++p;
	switch (yych) {
		case 'e': goto yy166;
		default: goto yy25;
	}
yy123:
	yych = *++p;
	switch (yych) {
		case '~': goto yy167;
		default: goto yy25;
	}
yy124:
	++p;
#line 175 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1453 "block_scanner_gen.h"
yy125:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy168;
yy126:
	++p;
#line 176 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1462 "block_scanner_gen.h"
yy127:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy170;
yy128:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy172;
		default: goto yy26;
	}
yy129:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy173;
		default: goto yy26;
	}
yy130:
	++p;
#line 156 "block_scanner.re"
	{ return AQ_BT_LIST_UNORD; }
#line 1487 "block_scanner_gen.h"
yy131:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy174;
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy175;
		default: goto yy25;
	}
yy132:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy176;
		case '+': goto yy177;
		default: goto yy25;
	}
yy133:
	++p;
#line 155 "block_scanner.re"
	{ return AQ_BT_LIST_UNORD; }
#line 1508 "block_scanner_gen.h"
yy134:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy178;
		case '-': goto yy179;
		default: goto yy25;
	}
yy135:
	++p;
#line 144 "block_scanner.re"
	{ return AQ_BT_LIST_ORD; }
#line 1520 "block_scanner_gen.h"
yy136:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy180;
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy181;
		default: goto yy25;
	}
yy137:
	++p;
#line 71 "block_scanner.re"
	{ return AQ_BT_COMMENT; }
#line 1534 "block_scanner_gen.h"
yy138:
	yych = *++p;
	if (yych <= 0x00) goto yy182;
	goto yy25;
yy139:
	yych = *++p;
	if (yych <= 0x00) goto yy183;
	goto yy139;
yy140:
	++p;
#line 79 "block_scanner.re"
	{
        return AQ_BT_ATTR_ENTRY;
    }
#line 1549 "block_scanner_gen.h"
yy141:
	yych = *++p;
	if (yych <= 0x00) goto yy140;
	goto yy141;
yy142:
	yych = *++p;
	if (yych <= 0x00) goto yy184;
	goto yy142;
yy143:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy98;
		case '\t':
		case ' ': goto yy99;
		case ':': goto yy74;
		default: goto yy25;
	}
yy144:
	yych = *++p;
	if (yych <= 0x00) goto yy185;
	goto yy144;
yy145:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy145;
		default: goto yy186;
	}
yy146:
	++p;
#line 63 "block_scanner.re"
	{ return AQ_BT_PAGE_BREAK; }
#line 1583 "block_scanner_gen.h"
yy147:
	++p;
#line 84 "block_scanner.re"
	{ return AQ_BT_SECTION_TITLE; }
#line 1588 "block_scanner_gen.h"
yy148:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy187;
		case '\t':
		case ' ': goto yy55;
		case '=': goto yy188;
		default: goto yy25;
	}
yy149:
	yych = *++p;
	if (yych <= 0x00) goto yy189;
	goto yy149;
yy150:
	yych = *++p;
	if (yych <= 0x00) goto yy190;
	goto yy150;
yy151:
	yych = *++p;
	if (yych <= 0x00) goto yy191;
	goto yy151;
yy152:
	++p;
#line 130 "block_scanner.re"
	{ return AQ_BT_BLOCK_ATTR; }
#line 1614 "block_scanner_gen.h"
yy153:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy193;
yy154:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy196;
yy155:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy199;
		case ';': goto yy156;
		case ']': goto yy157;
		default: goto yy113;
	}
yy156:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy155;
		case ';': goto yy200;
		case ']': goto yy157;
		default: goto yy113;
	}
yy157:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy155;
		case ';': goto yy156;
		case ']': goto yy201;
		default: goto yy113;
	}
yy158:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy202;
		case '_': goto yy203;
		default: goto yy25;
	}
yy159:
	yych = *++p;
	switch (yych) {
		case 'o': goto yy204;
		default: goto yy25;
	}
yy160:
	yych = *++p;
	switch (yych) {
		case 'f': goto yy205;
		default: goto yy25;
	}
yy161:
	yych = *++p;
	switch (yych) {
		case 'f': goto yy206;
		default: goto yy25;
	}
yy162:
	yych = *++p;
	switch (yych) {
		case 'a': goto yy207;
		default: goto yy25;
	}
yy163:
	yych = *++p;
	switch (yych) {
		case 'e': goto yy208;
		default: goto yy25;
	}
yy164:
	yych = *++p;
	switch (yych) {
		case 'e': goto yy209;
		default: goto yy25;
	}
yy165:
	yych = *++p;
	switch (yych) {
		case 'u': goto yy210;
		default: goto yy25;
	}
yy166:
	yych = *++p;
	switch (yych) {
		case 'o': goto yy211;
		default: goto yy25;
	}
yy167:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy212;
		case ':': goto yy27;
		case ';': goto yy28;
		case '~': goto yy167;
		default: goto yy24;
	}
yy168:
	yych = *++p;
	if (yych <= 0x00) goto yy124;
	goto yy168;
yy169:
	yych = *++p;
yy170:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy171;
		default: goto yy169;
	}
yy171:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy213;
		default: goto yy169;
	}
yy172:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy214;
		default: goto yy26;
	}
yy173:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy215;
		default: goto yy26;
	}
yy174:
	++p;
#line 110 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1753 "block_scanner_gen.h"
yy175:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy216;
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy217;
		default: goto yy25;
	}
yy176:
	++p;
#line 111 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1767 "block_scanner_gen.h"
yy177:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy218;
		case '+': goto yy177;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy178:
	++p;
#line 106 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1781 "block_scanner_gen.h"
yy179:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy219;
		case '-': goto yy179;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy180:
	++p;
#line 107 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1795 "block_scanner_gen.h"
yy181:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy220;
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy221;
		default: goto yy25;
	}
yy182:
	++p;
#line 66 "block_scanner.re"
	{ return AQ_BT_BLOCK_COMMENT; }
#line 1809 "block_scanner_gen.h"
yy183:
	++p;
#line 146 "block_scanner.re"
	{ return AQ_BT_LIST_ORD; }
#line 1814 "block_scanner_gen.h"
yy184:
	++p;
#line 170 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1819 "block_scanner_gen.h"
yy185:
	++p;
#line 172 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1824 "block_scanner_gen.h"
yy186:
	yych = *++p;
	if (yych <= 0x00) goto yy222;
	goto yy186;
yy187:
	++p;
#line 108 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1833 "block_scanner_gen.h"
yy188:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy223;
		case '\t':
		case ' ': goto yy55;
		case '=': goto yy224;
		default: goto yy25;
	}
yy189:
	++p;
#line 152 "block_scanner.re"
	{ return AQ_BT_LIST_ORD; }
#line 1847 "block_scanner_gen.h"
yy190:
	++p;
#line 148 "block_scanner.re"
	{ return AQ_BT_LIST_ORD; }
#line 1852 "block_scanner_gen.h"
yy191:
	++p;
#line 150 "block_scanner.re"
	{ return AQ_BT_LIST_ORD; }
#line 1857 "block_scanner_gen.h"
yy192:
	yych = *++p;
yy193:
	switch (yych) {
		case 0x00: goto yy124;
		case ']': goto yy194;
		default: goto yy192;
	}
yy194:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy152;
		case ']': goto yy194;
		default: goto yy192;
	}
yy195:
	yych = *++p;
yy196:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy197;
		case ']': goto yy198;
		default: goto yy195;
	}
yy197:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy225;
		case ']': goto yy198;
		default: goto yy195;
	}
yy198:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy152;
		case ':': goto yy197;
		case ']': goto yy198;
		default: goto yy195;
	}
yy199:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy226;
		case ':': goto yy199;
		case ';': goto yy156;
		case ']': goto yy157;
		default: goto yy113;
	}
yy200:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy227;
		case ':': goto yy155;
		case ';': goto yy200;
		case ']': goto yy157;
		default: goto yy113;
	}
yy201:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy228;
		case ':': goto yy155;
		case ';': goto yy156;
		case ']': goto yy201;
		default: goto yy113;
	}
yy202:
	++p;
#line 109 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1933 "block_scanner_gen.h"
yy203:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy229;
		case ':': goto yy27;
		case ';': goto yy28;
		case '_': goto yy203;
		default: goto yy24;
	}
yy204:
	yych = *++p;
	switch (yych) {
		case ':': goto yy230;
		default: goto yy25;
	}
yy205:
	yych = *++p;
	switch (yych) {
		case ':': goto yy231;
		default: goto yy25;
	}
yy206:
	yych = *++p;
	switch (yych) {
		case ':': goto yy232;
		default: goto yy25;
	}
yy207:
	yych = *++p;
	switch (yych) {
		case 'l': goto yy233;
		default: goto yy25;
	}
yy208:
	yych = *++p;
	switch (yych) {
		case 'f': goto yy234;
		default: goto yy25;
	}
yy209:
	yych = *++p;
	switch (yych) {
		case ':': goto yy235;
		default: goto yy25;
	}
yy210:
	yych = *++p;
	switch (yych) {
		case 'd': goto yy236;
		default: goto yy25;
	}
yy211:
	yych = *++p;
	switch (yych) {
		case ':': goto yy237;
		default: goto yy25;
	}
yy212:
	++p;
#line 122 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1995 "block_scanner_gen.h"
yy213:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy238;
		case ':': goto yy213;
		default: goto yy169;
	}
yy214:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		default: goto yy26;
	}
yy215:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy43;
		default: goto yy26;
	}
yy216:
	++p;
#line 120 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 2023 "block_scanner_gen.h"
yy217:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy216;
		case '*': goto yy217;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy218:
	++p;
#line 121 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 2037 "block_scanner_gen.h"
yy219:
	++p;
#line 116 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 2042 "block_scanner_gen.h"
yy220:
	++p;
#line 117 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 2047 "block_scanner_gen.h"
yy221:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy220;
		case '.': goto yy221;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy222:
	++p;
#line 140 "block_scanner.re"
	{ return AQ_BT_LIST_CALLOUT; }
#line 2061 "block_scanner_gen.h"
yy223:
	++p;
#line 118 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 2066 "block_scanner_gen.h"
yy224:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy223;
		case '\t':
		case ' ': goto yy55;
		case '=': goto yy239;
		default: goto yy25;
	}
yy225:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy240;
		case ':': goto yy225;
		case ']': goto yy198;
		default: goto yy195;
	}
yy226:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy242;
yy227:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy245;
yy228:
	++p;
#line 125 "block_scanner.re"
	{ return AQ_BT_BLOCK_ANCHOR; }
#line 2098 "block_scanner_gen.h"
yy229:
	++p;
#line 119 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 2103 "block_scanner_gen.h"
yy230:
	yych = *++p;
	switch (yych) {
		case ':': goto yy248;
		default: goto yy25;
	}
yy231:
	yych = *++p;
	switch (yych) {
		case ':': goto yy249;
		default: goto yy25;
	}
yy232:
	yych = *++p;
	switch (yych) {
		case ':': goto yy250;
		default: goto yy25;
	}
yy233:
	yych = *++p;
	switch (yych) {
		case ':': goto yy251;
		default: goto yy25;
	}
yy234:
	yych = *++p;
	switch (yych) {
		case ':': goto yy252;
		default: goto yy25;
	}
yy235:
	yych = *++p;
	switch (yych) {
		case ':': goto yy253;
		default: goto yy25;
	}
yy236:
	yych = *++p;
	switch (yych) {
		case 'e': goto yy254;
		default: goto yy25;
	}
yy237:
	yych = *++p;
	switch (yych) {
		case ':': goto yy255;
		default: goto yy25;
	}
yy238:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy168;
yy239:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy223;
		case ':': goto yy27;
		case ';': goto yy28;
		case '=': goto yy239;
		default: goto yy24;
	}
yy240:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy193;
yy241:
	yych = *++p;
yy242:
	switch (yych) {
		case 0x00: goto yy124;
		case ']': goto yy243;
		default: goto yy241;
	}
yy243:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case ']': goto yy256;
		default: goto yy241;
	}
yy244:
	yych = *++p;
yy245:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy246;
		case ']': goto yy247;
		default: goto yy244;
	}
yy246:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy257;
		case ']': goto yy247;
		default: goto yy244;
	}
yy247:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy246;
		case ']': goto yy258;
		default: goto yy244;
	}
yy248:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy125;
		case '[': goto yy259;
		default: goto yy261;
	}
yy249:
	yych = *++p;
	if (yych <= 0x00) goto yy263;
	goto yy249;
yy250:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy125;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy264;
		case ':': goto yy74;
		default: goto yy25;
	}
yy251:
	yych = *++p;
	switch (yych) {
		case ':': goto yy265;
		default: goto yy25;
	}
yy252:
	yych = *++p;
	switch (yych) {
		case ':': goto yy266;
		default: goto yy25;
	}
yy253:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy125;
		case '[': goto yy267;
		default: goto yy269;
	}
yy254:
	yych = *++p;
	switch (yych) {
		case ':': goto yy271;
		default: goto yy25;
	}
yy255:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy125;
		case '[': goto yy272;
		default: goto yy274;
	}
yy256:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy228;
		case ']': goto yy256;
		default: goto yy241;
	}
yy257:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy276;
		case ':': goto yy257;
		case ']': goto yy247;
		default: goto yy244;
	}
yy258:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy228;
		case ':': goto yy246;
		case ']': goto yy258;
		default: goto yy244;
	}
yy259:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy277;
		case ';': goto yy262;
		case '[': goto yy278;
		default: goto yy259;
	}
yy260:
	yych = *++p;
yy261:
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy279;
		case ':': goto yy260;
		case ';': goto yy262;
		case '[': goto yy278;
		default: goto yy259;
	}
yy262:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy277;
		case ';': goto yy280;
		case '[': goto yy278;
		default: goto yy259;
	}
yy263:
	++p;
#line 97 "block_scanner.re"
	{ return AQ_BT_ENDIF;  }
#line 2386 "block_scanner_gen.h"
yy264:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy281;
		case ';': goto yy282;
		case '[': goto yy283;
		default: goto yy264;
	}
yy265:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy125;
		case ':': goto yy74;
		case '[': goto yy284;
		default: goto yy25;
	}
yy266:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy125;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy285;
		case ':': goto yy74;
		default: goto yy25;
	}
yy267:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy286;
		case ';': goto yy270;
		case '[': goto yy287;
		default: goto yy267;
	}
yy268:
	yych = *++p;
yy269:
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy288;
		case ':': goto yy268;
		case ';': goto yy270;
		case '[': goto yy287;
		default: goto yy267;
	}
yy270:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy286;
		case ';': goto yy289;
		case '[': goto yy287;
		default: goto yy267;
	}
yy271:
	yych = *++p;
	switch (yych) {
		case ':': goto yy290;
		default: goto yy25;
	}
yy272:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy291;
		case ';': goto yy275;
		case '[': goto yy292;
		default: goto yy272;
	}
yy273:
	yych = *++p;
yy274:
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy293;
		case ':': goto yy273;
		case ';': goto yy275;
		case '[': goto yy292;
		default: goto yy272;
	}
yy275:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy291;
		case ';': goto yy294;
		case '[': goto yy292;
		default: goto yy272;
	}
yy276:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy242;
yy277:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy260;
		case ';': goto yy262;
		case '[': goto yy278;
		default: goto yy259;
	}
yy278:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy295;
		case ';': goto yy296;
		case ']': goto yy297;
		default: goto yy278;
	}
yy279:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy299;
yy280:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy302;
		case ':': goto yy277;
		case ';': goto yy280;
		case '[': goto yy278;
		default: goto yy259;
	}
yy281:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy303;
		case ';': goto yy282;
		case '[': goto yy283;
		default: goto yy264;
	}
yy282:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy281;
		case ';': goto yy304;
		case '[': goto yy283;
		default: goto yy264;
	}
yy283:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy305;
		case ';': goto yy306;
		case ']': goto yy307;
		default: goto yy283;
	}
yy284:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy308;
		case ';': goto yy309;
		case ']': goto yy310;
		default: goto yy284;
	}
yy285:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy311;
		case ';': goto yy312;
		case '[': goto yy313;
		default: goto yy285;
	}
yy286:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy268;
		case ';': goto yy270;
		case '[': goto yy287;
		default: goto yy267;
	}
yy287:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy314;
		case ';': goto yy315;
		case ']': goto yy316;
		default: goto yy287;
	}
yy288:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy318;
yy289:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy321;
		case ':': goto yy286;
		case ';': goto yy289;
		case '[': goto yy287;
		default: goto yy267;
	}
yy290:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy125;
		case '[': goto yy322;
		default: goto yy324;
	}
yy291:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy273;
		case ';': goto yy275;
		case '[': goto yy292;
		default: goto yy272;
	}
yy292:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy326;
		case ';': goto yy327;
		case ']': goto yy328;
		default: goto yy292;
	}
yy293:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy330;
yy294:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy333;
		case ':': goto yy291;
		case ';': goto yy294;
		case '[': goto yy292;
		default: goto yy272;
	}
yy295:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy334;
		case ';': goto yy296;
		case ']': goto yy297;
		default: goto yy278;
	}
yy296:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy295;
		case ';': goto yy335;
		case ']': goto yy297;
		default: goto yy278;
	}
yy297:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy336;
		case ':': goto yy295;
		case ';': goto yy296;
		case ']': goto yy297;
		default: goto yy278;
	}
yy298:
	yych = *++p;
yy299:
	switch (yych) {
		case 0x00: goto yy124;
		case '[': goto yy300;
		default: goto yy298;
	}
yy300:
	yych = *++p;
yy301:
	switch (yych) {
		case 0x00: goto yy124;
		case ']': goto yy337;
		default: goto yy300;
	}
yy302:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy339;
yy303:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy343;
		case ':': goto yy303;
		case ';': goto yy282;
		case '[': goto yy283;
		default: goto yy264;
	}
yy304:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy344;
		case ':': goto yy281;
		case ';': goto yy304;
		case '[': goto yy283;
		default: goto yy264;
	}
yy305:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy345;
		case ';': goto yy306;
		case ']': goto yy307;
		default: goto yy283;
	}
yy306:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy305;
		case ';': goto yy346;
		case ']': goto yy307;
		default: goto yy283;
	}
yy307:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy347;
		case ':': goto yy305;
		case ';': goto yy306;
		case ']': goto yy307;
		default: goto yy283;
	}
yy308:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy348;
		case ';': goto yy309;
		case ']': goto yy310;
		default: goto yy284;
	}
yy309:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy308;
		case ';': goto yy349;
		case ']': goto yy310;
		default: goto yy284;
	}
yy310:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy350;
		case ':': goto yy308;
		case ';': goto yy309;
		case ']': goto yy310;
		default: goto yy284;
	}
yy311:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy351;
		case ';': goto yy312;
		case '[': goto yy313;
		default: goto yy285;
	}
yy312:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy311;
		case ';': goto yy352;
		case '[': goto yy313;
		default: goto yy285;
	}
yy313:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy353;
		case ';': goto yy354;
		case ']': goto yy355;
		default: goto yy313;
	}
yy314:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy356;
		case ';': goto yy315;
		case ']': goto yy316;
		default: goto yy287;
	}
yy315:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy314;
		case ';': goto yy357;
		case ']': goto yy316;
		default: goto yy287;
	}
yy316:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy358;
		case ':': goto yy314;
		case ';': goto yy315;
		case ']': goto yy316;
		default: goto yy287;
	}
yy317:
	yych = *++p;
yy318:
	switch (yych) {
		case 0x00: goto yy124;
		case '[': goto yy319;
		default: goto yy317;
	}
yy319:
	yych = *++p;
yy320:
	switch (yych) {
		case 0x00: goto yy124;
		case ']': goto yy359;
		default: goto yy319;
	}
yy321:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy361;
yy322:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy365;
		case ';': goto yy325;
		case '[': goto yy366;
		default: goto yy322;
	}
yy323:
	yych = *++p;
yy324:
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy367;
		case ':': goto yy323;
		case ';': goto yy325;
		case '[': goto yy366;
		default: goto yy322;
	}
yy325:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy365;
		case ';': goto yy368;
		case '[': goto yy366;
		default: goto yy322;
	}
yy326:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy369;
		case ';': goto yy327;
		case ']': goto yy328;
		default: goto yy292;
	}
yy327:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy326;
		case ';': goto yy370;
		case ']': goto yy328;
		default: goto yy292;
	}
yy328:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy371;
		case ':': goto yy326;
		case ';': goto yy327;
		case ']': goto yy328;
		default: goto yy292;
	}
yy329:
	yych = *++p;
yy330:
	switch (yych) {
		case 0x00: goto yy124;
		case '[': goto yy331;
		default: goto yy329;
	}
yy331:
	yych = *++p;
yy332:
	switch (yych) {
		case 0x00: goto yy124;
		case ']': goto yy372;
		default: goto yy331;
	}
yy333:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy374;
yy334:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy378;
		case ':': goto yy334;
		case ';': goto yy296;
		case ']': goto yy297;
		default: goto yy278;
	}
yy335:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy379;
		case ':': goto yy295;
		case ';': goto yy335;
		case ']': goto yy297;
		default: goto yy278;
	}
yy336:
	++p;
#line 91 "block_scanner.re"
	{ return AQ_BT_BLOCK_MEDIA; }
#line 3000 "block_scanner_gen.h"
yy337:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy336;
		case ']': goto yy337;
		default: goto yy300;
	}
yy338:
	yych = *++p;
yy339:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy340;
		case '[': goto yy341;
		default: goto yy338;
	}
yy340:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy380;
		case '[': goto yy341;
		default: goto yy338;
	}
yy341:
	yych = *++p;
yy342:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy381;
		case ']': goto yy382;
		default: goto yy341;
	}
yy343:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy384;
yy344:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy388;
yy345:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy392;
		case ':': goto yy345;
		case ';': goto yy306;
		case ']': goto yy307;
		default: goto yy283;
	}
yy346:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy393;
		case ':': goto yy305;
		case ';': goto yy346;
		case ']': goto yy307;
		default: goto yy283;
	}
yy347:
	++p;
#line 94 "block_scanner.re"
	{ return AQ_BT_IFDEF;  }
#line 3068 "block_scanner_gen.h"
yy348:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy394;
		case ':': goto yy348;
		case ';': goto yy309;
		case ']': goto yy310;
		default: goto yy284;
	}
yy349:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy395;
		case ':': goto yy308;
		case ';': goto yy349;
		case ']': goto yy310;
		default: goto yy284;
	}
yy350:
	++p;
#line 96 "block_scanner.re"
	{ return AQ_BT_IFEVAL; }
#line 3095 "block_scanner_gen.h"
yy351:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy396;
		case ':': goto yy351;
		case ';': goto yy312;
		case '[': goto yy313;
		default: goto yy285;
	}
yy352:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy397;
		case ':': goto yy311;
		case ';': goto yy352;
		case '[': goto yy313;
		default: goto yy285;
	}
yy353:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy398;
		case ';': goto yy354;
		case ']': goto yy355;
		default: goto yy313;
	}
yy354:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy353;
		case ';': goto yy399;
		case ']': goto yy355;
		default: goto yy313;
	}
yy355:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy400;
		case ':': goto yy353;
		case ';': goto yy354;
		case ']': goto yy355;
		default: goto yy313;
	}
yy356:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy401;
		case ':': goto yy356;
		case ';': goto yy315;
		case ']': goto yy316;
		default: goto yy287;
	}
yy357:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy402;
		case ':': goto yy314;
		case ';': goto yy357;
		case ']': goto yy316;
		default: goto yy287;
	}
yy358:
	++p;
#line 87 "block_scanner.re"
	{ return AQ_BT_BLOCK_IMAGE; }
#line 3171 "block_scanner_gen.h"
yy359:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy358;
		case ']': goto yy359;
		default: goto yy319;
	}
yy360:
	yych = *++p;
yy361:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy362;
		case '[': goto yy363;
		default: goto yy360;
	}
yy362:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy403;
		case '[': goto yy363;
		default: goto yy360;
	}
yy363:
	yych = *++p;
yy364:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy404;
		case ']': goto yy405;
		default: goto yy363;
	}
yy365:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy323;
		case ';': goto yy325;
		case '[': goto yy366;
		default: goto yy322;
	}
yy366:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy406;
		case ';': goto yy407;
		case ']': goto yy408;
		default: goto yy366;
	}
yy367:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy410;
yy368:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy413;
		case ':': goto yy365;
		case ';': goto yy368;
		case '[': goto yy366;
		default: goto yy322;
	}
yy369:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy414;
		case ':': goto yy369;
		case ';': goto yy327;
		case ']': goto yy328;
		default: goto yy292;
	}
yy370:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy415;
		case ':': goto yy326;
		case ';': goto yy370;
		case ']': goto yy328;
		default: goto yy292;
	}
yy371:
	++p;
#line 90 "block_scanner.re"
	{ return AQ_BT_BLOCK_MEDIA; }
#line 3264 "block_scanner_gen.h"
yy372:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy371;
		case ']': goto yy372;
		default: goto yy331;
	}
yy373:
	yych = *++p;
yy374:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy375;
		case '[': goto yy376;
		default: goto yy373;
	}
yy375:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy416;
		case '[': goto yy376;
		default: goto yy373;
	}
yy376:
	yych = *++p;
yy377:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy417;
		case ']': goto yy418;
		default: goto yy376;
	}
yy378:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy301;
yy379:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy342;
yy380:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy419;
		case ':': goto yy380;
		case '[': goto yy341;
		default: goto yy338;
	}
yy381:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy420;
		case ']': goto yy382;
		default: goto yy341;
	}
yy382:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy336;
		case ':': goto yy381;
		case ']': goto yy382;
		default: goto yy341;
	}
yy383:
	yych = *++p;
yy384:
	switch (yych) {
		case 0x00: goto yy124;
		case '[': goto yy385;
		default: goto yy383;
	}
yy385:
	yych = *++p;
yy386:
	switch (yych) {
		case 0x00: goto yy124;
		case ']': goto yy421;
		default: goto yy385;
	}
yy387:
	yych = *++p;
yy388:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy389;
		case '[': goto yy390;
		default: goto yy387;
	}
yy389:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy422;
		case '[': goto yy390;
		default: goto yy387;
	}
yy390:
	yych = *++p;
yy391:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy423;
		case ']': goto yy424;
		default: goto yy390;
	}
yy392:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy386;
yy393:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy391;
yy394:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy426;
yy395:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy429;
yy396:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy433;
yy397:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy437;
yy398:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy441;
		case ':': goto yy398;
		case ';': goto yy354;
		case ']': goto yy355;
		default: goto yy313;
	}
yy399:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy442;
		case ':': goto yy353;
		case ';': goto yy399;
		case ']': goto yy355;
		default: goto yy313;
	}
yy400:
	++p;
#line 95 "block_scanner.re"
	{ return AQ_BT_IFNDEF; }
#line 3424 "block_scanner_gen.h"
yy401:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy320;
yy402:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy364;
yy403:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy443;
		case ':': goto yy403;
		case '[': goto yy363;
		default: goto yy360;
	}
yy404:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy444;
		case ']': goto yy405;
		default: goto yy363;
	}
yy405:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy358;
		case ':': goto yy404;
		case ']': goto yy405;
		default: goto yy363;
	}
yy406:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy445;
		case ';': goto yy407;
		case ']': goto yy408;
		default: goto yy366;
	}
yy407:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy406;
		case ';': goto yy446;
		case ']': goto yy408;
		default: goto yy366;
	}
yy408:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy447;
		case ':': goto yy406;
		case ';': goto yy407;
		case ']': goto yy408;
		default: goto yy366;
	}
yy409:
	yych = *++p;
yy410:
	switch (yych) {
		case 0x00: goto yy124;
		case '[': goto yy411;
		default: goto yy409;
	}
yy411:
	yych = *++p;
yy412:
	switch (yych) {
		case 0x00: goto yy124;
		case ']': goto yy448;
		default: goto yy411;
	}
yy413:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy450;
yy414:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy332;
yy415:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy377;
yy416:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy454;
		case ':': goto yy416;
		case '[': goto yy376;
		default: goto yy373;
	}
yy417:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy455;
		case ']': goto yy418;
		default: goto yy376;
	}
yy418:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy371;
		case ':': goto yy417;
		case ']': goto yy418;
		default: goto yy376;
	}
yy419:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy299;
yy420:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy456;
		case ':': goto yy420;
		case ']': goto yy382;
		default: goto yy341;
	}
yy421:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy347;
		case ']': goto yy421;
		default: goto yy385;
	}
yy422:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy457;
		case ':': goto yy422;
		case '[': goto yy390;
		default: goto yy387;
	}
yy423:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy458;
		case ']': goto yy424;
		default: goto yy390;
	}
yy424:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy347;
		case ':': goto yy423;
		case ']': goto yy424;
		default: goto yy390;
	}
yy425:
	yych = *++p;
yy426:
	switch (yych) {
		case 0x00: goto yy124;
		case ']': goto yy427;
		default: goto yy425;
	}
yy427:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy350;
		case ']': goto yy427;
		default: goto yy425;
	}
yy428:
	yych = *++p;
yy429:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy430;
		case ']': goto yy431;
		default: goto yy428;
	}
yy430:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy459;
		case ']': goto yy431;
		default: goto yy428;
	}
yy431:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy350;
		case ':': goto yy430;
		case ']': goto yy431;
		default: goto yy428;
	}
yy432:
	yych = *++p;
yy433:
	switch (yych) {
		case 0x00: goto yy124;
		case '[': goto yy434;
		default: goto yy432;
	}
yy434:
	yych = *++p;
yy435:
	switch (yych) {
		case 0x00: goto yy124;
		case ']': goto yy460;
		default: goto yy434;
	}
yy436:
	yych = *++p;
yy437:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy438;
		case '[': goto yy439;
		default: goto yy436;
	}
yy438:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy461;
		case '[': goto yy439;
		default: goto yy436;
	}
yy439:
	yych = *++p;
yy440:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy462;
		case ']': goto yy463;
		default: goto yy439;
	}
yy441:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy435;
yy442:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy440;
yy443:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy318;
yy444:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy464;
		case ':': goto yy444;
		case ']': goto yy405;
		default: goto yy363;
	}
yy445:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy465;
		case ':': goto yy445;
		case ';': goto yy407;
		case ']': goto yy408;
		default: goto yy366;
	}
yy446:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case '\t':
		case ' ': goto yy466;
		case ':': goto yy406;
		case ';': goto yy446;
		case ']': goto yy408;
		default: goto yy366;
	}
yy447:
	++p;
#line 100 "block_scanner.re"
	{ return AQ_BT_INCLUDE; }
#line 3717 "block_scanner_gen.h"
yy448:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy447;
		case ']': goto yy448;
		default: goto yy411;
	}
yy449:
	yych = *++p;
yy450:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy451;
		case '[': goto yy452;
		default: goto yy449;
	}
yy451:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy467;
		case '[': goto yy452;
		default: goto yy449;
	}
yy452:
	yych = *++p;
yy453:
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy468;
		case ']': goto yy469;
		default: goto yy452;
	}
yy454:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy330;
yy455:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy470;
		case ':': goto yy455;
		case ']': goto yy418;
		default: goto yy376;
	}
yy456:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy301;
yy457:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy384;
yy458:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy471;
		case ':': goto yy458;
		case ']': goto yy424;
		default: goto yy390;
	}
yy459:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy472;
		case ':': goto yy459;
		case ']': goto yy431;
		default: goto yy428;
	}
yy460:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy400;
		case ']': goto yy460;
		default: goto yy434;
	}
yy461:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy473;
		case ':': goto yy461;
		case '[': goto yy439;
		default: goto yy436;
	}
yy462:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy474;
		case ']': goto yy463;
		default: goto yy439;
	}
yy463:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy400;
		case ':': goto yy462;
		case ']': goto yy463;
		default: goto yy439;
	}
yy464:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy320;
yy465:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy412;
yy466:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy453;
yy467:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy475;
		case ':': goto yy467;
		case '[': goto yy452;
		default: goto yy449;
	}
yy468:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy126;
		case ':': goto yy476;
		case ']': goto yy469;
		default: goto yy452;
	}
yy469:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy447;
		case ':': goto yy468;
		case ']': goto yy469;
		default: goto yy452;
	}
yy470:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy332;
yy471:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy386;
yy472:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy426;
yy473:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy433;
yy474:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy477;
		case ':': goto yy474;
		case ']': goto yy463;
		default: goto yy439;
	}
yy475:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy410;
yy476:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy124;
		case '\t':
		case ' ': goto yy478;
		case ':': goto yy476;
		case ']': goto yy469;
		default: goto yy452;
	}
yy477:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy435;
yy478:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy412;
}
#line 181 "block_scanner.re"

}
