/* Generated by re2c 3.1 */
#line 1 "block_scanner.re"
// @file block_scanner.re
// @brief re2c source for the AsciiDoc block-level line scanner.
//
// This file is compiled by re2c to produce block_scanner_gen.h.
// Command: re2c --no-generation-date -W -o block_scanner_gen.h block_scanner.re
//
// A pre-generated copy is committed as block_scanner_gen.h so that re2c is
// NOT required at build time.  When USE_RE2C=ON and re2c is found by CMake,
// the file is regenerated automatically.
// Design notes:
// -------------
// * The input is a single AsciiDoc line passed as (const char*, size_t len)
//   where line[len] == '\0'.  std::string::c_str()/size() is always correct.
// * Rules are ordered so more specific patterns appear first; re2c uses the
//   FIRST matching rule on ties (same length).
// * Comment lines ("//...") appear before description-list rules, providing
//   the same guard as the (?!//[^/]) negative lookahead in the PCRE2 pattern.
// * Thematic-break patterns that require backreferences (e.g., the "---" /
//   "* * *" / "_ _ _" family using ([-*_])( *)\1\2\1) are NOT handled here.
//   The wrapper in block_scanner.c detects them with a fast C function BEFORE
//   calling aq_classify_line().  This keeps the re2c DFA free of patterns
//   that are inherently non-regular.
// * Delimited-block fence rules cover 2 characters ("--") through 4+.
//   The three-character fence ("---", "...") is intentionally absent so that
//   it falls through to the AQ_BT_TEXT default, allowing the wrapper's
//   thematic-break pre-check to reclaim it.

#include "block_scanner.h"
#include <stddef.h>

/* ── Internal DFA classifier ─────────────────────────────────────────────────
 *
 * Called by aq_scan_block_line() AFTER the thematic-break pre-check.
 * Returns the broad token type; capture extraction is done by the wrapper.
 */
static AqBlockToken aq_classify_line(const char *p, size_t len)
{
    const char *pe       = p + len;  /* NUL sentinel is at *pe  */
    const char *YYMARKER = p;        /* backtrack marker         */
    (void)YYMARKER;
    (void)pe;  /* YYLIMIT alias; unused when yyfill:enable = 0 */

    
#line 47 "block_scanner_gen.h"
{
	unsigned char yych;
	yych = *p;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case ' ': goto yy4;
		case '*': goto yy5;
		case '+': goto yy6;
		case '-': goto yy7;
		case '.': goto yy8;
		case '/': goto yy9;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy10;
		case ':': goto yy11;
		case ';': goto yy12;
		case '<': goto yy13;
		case '=': goto yy14;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'W':
		case 'Y':
		case 'Z':
		case 'b':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'w':
		case 'y':
		case 'z': goto yy15;
		case 'I':
		case 'V':
		case 'X':
		case 'x': goto yy16;
		case '[': goto yy17;
		case '_': goto yy18;
		case 'a': goto yy19;
		case 'e': goto yy20;
		case 'i': goto yy21;
		case 'v': goto yy22;
		case '~': goto yy23;
		default: goto yy2;
	}
yy1:
	++p;
#line 60 "block_scanner.re"
	{ return AQ_BT_BLANK; }
#line 135 "block_scanner_gen.h"
yy2:
	yych = *(YYMARKER = ++p);
	if (yych >= 0x01) goto yy25;
yy3:
#line 177 "block_scanner.re"
	{ return AQ_BT_TEXT; }
#line 142 "block_scanner_gen.h"
yy4:
	yych = *(YYMARKER = ++p);
	goto yy30;
yy5:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy38;
		default: goto yy25;
	}
yy6:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '+': goto yy39;
		default: goto yy25;
	}
yy7:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '\t':
		case ' ': goto yy40;
		case '-': goto yy41;
		default: goto yy25;
	}
yy8:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ' ': goto yy43;
		case '.': goto yy44;
		default: goto yy42;
	}
yy9:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '/': goto yy45;
		default: goto yy25;
	}
yy10:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '.': goto yy46;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy34;
		default: goto yy25;
	}
yy11:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '!': goto yy47;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy48;
		case ':': goto yy49;
		default: goto yy25;
	}
yy12:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ';': goto yy50;
		default: goto yy25;
	}
yy13:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '.': goto yy51;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy52;
		case '<': goto yy53;
		default: goto yy25;
	}
yy14:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '\t':
		case ' ': goto yy54;
		case '=': goto yy55;
		default: goto yy25;
	}
yy15:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '.': goto yy56;
		default: goto yy25;
	}
yy16:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ')': goto yy57;
		case '.': goto yy56;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy58;
		default: goto yy25;
	}
yy17:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '[': goto yy63;
		case ']': goto yy24;
		default: goto yy60;
	}
yy18:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '_': goto yy64;
		default: goto yy25;
	}
yy19:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '.': goto yy56;
		case 'u': goto yy65;
		default: goto yy25;
	}
yy20:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '.': goto yy56;
		case 'n': goto yy66;
		default: goto yy25;
	}
yy21:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ')': goto yy57;
		case '.': goto yy56;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy58;
		case 'f': goto yy67;
		case 'm': goto yy68;
		case 'n': goto yy69;
		default: goto yy25;
	}
yy22:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case ')': goto yy57;
		case '.': goto yy56;
		case 'I':
		case 'V':
		case 'X':
		case 'v':
		case 'x': goto yy58;
		case 'i': goto yy70;
		default: goto yy25;
	}
yy23:
	yych = *(YYMARKER = ++p);
	switch (yych) {
		case 0x00: goto yy3;
		case '~': goto yy71;
		default: goto yy25;
	}
yy24:
	yych = *++p;
yy25:
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy26:
	p = YYMARKER;
	goto yy3;
yy27:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy72;
		case ';': goto yy28;
		default: goto yy24;
	}
yy28:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy27;
		case ';': goto yy73;
		default: goto yy24;
	}
yy29:
	yych = *++p;
yy30:
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case ' ': goto yy29;
		case '*': goto yy31;
		case '-': goto yy32;
		case '.': goto yy33;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy34;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'W':
		case 'Y':
		case 'Z':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'w':
		case 'y':
		case 'z': goto yy35;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy36;
		default: goto yy24;
	}
yy31:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy74;
		default: goto yy25;
	}
yy32:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy40;
		default: goto yy25;
	}
yy33:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy33;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy34:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '.': goto yy46;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy34;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy35:
	yych = *++p;
	switch (yych) {
		case '.': goto yy56;
		default: goto yy25;
	}
yy36:
	yych = *++p;
	switch (yych) {
		case ')': goto yy57;
		case '.': goto yy56;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy58;
		default: goto yy25;
	}
yy37:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy37;
		default: goto yy75;
	}
yy38:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy76;
		default: goto yy25;
	}
yy39:
	yych = *++p;
	switch (yych) {
		case '+': goto yy77;
		default: goto yy25;
	}
yy40:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy40;
		default: goto yy78;
	}
yy41:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy79;
		case '-': goto yy80;
		default: goto yy25;
	}
yy42:
	yych = *++p;
	if (yych <= 0x00) goto yy81;
	goto yy42;
yy43:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy43;
		default: goto yy82;
	}
yy44:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy83;
		default: goto yy25;
	}
yy45:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy84;
		case '/': goto yy86;
		default: goto yy85;
	}
yy46:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy87;
		default: goto yy25;
	}
yy47:
	yych = *++p;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy48;
		default: goto yy25;
	}
yy48:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ' ':
		case '\'':
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy48;
		case ':': goto yy88;
		case ';': goto yy28;
		default: goto yy24;
	}
yy49:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy89;
		case '\t':
		case ' ': goto yy90;
		case ':': goto yy91;
		default: goto yy25;
	}
yy50:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy92;
		case '\t':
		case ' ': goto yy93;
		case ';': goto yy73;
		default: goto yy25;
	}
yy51:
	yych = *++p;
	switch (yych) {
		case '>': goto yy94;
		default: goto yy25;
	}
yy52:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy52;
		case ':': goto yy27;
		case ';': goto yy28;
		case '>': goto yy94;
		default: goto yy24;
	}
yy53:
	yych = *++p;
	switch (yych) {
		case '<': goto yy95;
		default: goto yy25;
	}
yy54:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy54;
		default: goto yy96;
	}
yy55:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy54;
		case '=': goto yy97;
		default: goto yy25;
	}
yy56:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy98;
		default: goto yy25;
	}
yy57:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy99;
		default: goto yy25;
	}
yy58:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ')': goto yy57;
		case ':': goto yy27;
		case ';': goto yy28;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy58;
		default: goto yy24;
	}
yy59:
	yych = *++p;
yy60:
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy61;
		case ';': goto yy62;
		case ']': goto yy100;
		default: goto yy59;
	}
yy61:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy101;
		case ';': goto yy62;
		case ']': goto yy100;
		default: goto yy59;
	}
yy62:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy61;
		case ';': goto yy102;
		case ']': goto yy100;
		default: goto yy59;
	}
yy63:
	yych = *++p;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy103;
		default: goto yy25;
	}
yy64:
	yych = *++p;
	switch (yych) {
		case '_': goto yy104;
		default: goto yy25;
	}
yy65:
	yych = *++p;
	switch (yych) {
		case 'd': goto yy105;
		default: goto yy25;
	}
yy66:
	yych = *++p;
	switch (yych) {
		case 'd': goto yy106;
		default: goto yy25;
	}
yy67:
	yych = *++p;
	switch (yych) {
		case 'd': goto yy107;
		case 'e': goto yy108;
		case 'n': goto yy109;
		default: goto yy25;
	}
yy68:
	yych = *++p;
	switch (yych) {
		case 'a': goto yy110;
		default: goto yy25;
	}
yy69:
	yych = *++p;
	switch (yych) {
		case 'c': goto yy111;
		default: goto yy25;
	}
yy70:
	yych = *++p;
	switch (yych) {
		case ')': goto yy57;
		case 'I':
		case 'V':
		case 'X':
		case 'i':
		case 'v':
		case 'x': goto yy58;
		case 'd': goto yy112;
		default: goto yy25;
	}
yy71:
	yych = *++p;
	switch (yych) {
		case '~': goto yy113;
		default: goto yy25;
	}
yy72:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy115;
		case ':': goto yy72;
		case ';': goto yy28;
		default: goto yy24;
	}
yy73:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy117;
		case ':': goto yy27;
		case ';': goto yy73;
		default: goto yy24;
	}
yy74:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy118;
		default: goto yy25;
	}
yy75:
	yych = *++p;
	if (yych <= 0x00) goto yy119;
	goto yy75;
yy76:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy120;
		default: goto yy25;
	}
yy77:
	yych = *++p;
	switch (yych) {
		case '+': goto yy121;
		default: goto yy25;
	}
yy78:
	yych = *++p;
	if (yych <= 0x00) goto yy122;
	goto yy78;
yy79:
	++p;
#line 104 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1078 "block_scanner_gen.h"
yy80:
	yych = *++p;
	switch (yych) {
		case '-': goto yy123;
		default: goto yy25;
	}
yy81:
	++p;
#line 137 "block_scanner.re"
	{ return AQ_BT_BLOCK_TITLE; }
#line 1089 "block_scanner_gen.h"
yy82:
	yych = *++p;
	if (yych <= 0x00) goto yy124;
	goto yy82;
yy83:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy125;
		default: goto yy25;
	}
yy84:
	++p;
#line 72 "block_scanner.re"
	{ return AQ_BT_COMMENT; }
#line 1106 "block_scanner_gen.h"
yy85:
	yych = *++p;
	if (yych <= 0x00) goto yy126;
	goto yy85;
yy86:
	yych = *++p;
	switch (yych) {
		case '/': goto yy127;
		default: goto yy25;
	}
yy87:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy87;
		default: goto yy128;
	}
yy88:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy129;
		case '\t':
		case ' ': goto yy130;
		case ':': goto yy72;
		default: goto yy25;
	}
yy89:
	++p;
#line 168 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1138 "block_scanner_gen.h"
yy90:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy131;
yy91:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy89;
		case '\t':
		case ' ': goto yy90;
		case ':': goto yy132;
		default: goto yy25;
	}
yy92:
	++p;
#line 170 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1156 "block_scanner_gen.h"
yy93:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy133;
yy94:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy134;
		default: goto yy25;
	}
yy95:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy135;
		case ':': goto yy27;
		case ';': goto yy28;
		case '<': goto yy95;
		default: goto yy24;
	}
yy96:
	yych = *++p;
	if (yych <= 0x00) goto yy136;
	goto yy96;
yy97:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy54;
		case '=': goto yy137;
		default: goto yy25;
	}
yy98:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy98;
		default: goto yy138;
	}
yy99:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy99;
		default: goto yy139;
	}
yy100:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy140;
		case ':': goto yy61;
		case ';': goto yy62;
		case ']': goto yy100;
		default: goto yy59;
	}
yy101:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy141;
		case ':': goto yy101;
		case ';': goto yy62;
		case ']': goto yy100;
		default: goto yy59;
	}
yy102:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy142;
		case ':': goto yy61;
		case ';': goto yy102;
		case ']': goto yy100;
		default: goto yy59;
	}
yy103:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy143;
		case ';': goto yy144;
		case ']': goto yy145;
		default: goto yy103;
	}
yy104:
	yych = *++p;
	switch (yych) {
		case '_': goto yy146;
		default: goto yy25;
	}
yy105:
	yych = *++p;
	switch (yych) {
		case 'i': goto yy147;
		default: goto yy25;
	}
yy106:
	yych = *++p;
	switch (yych) {
		case 'i': goto yy148;
		default: goto yy25;
	}
yy107:
	yych = *++p;
	switch (yych) {
		case 'e': goto yy149;
		default: goto yy25;
	}
yy108:
	yych = *++p;
	switch (yych) {
		case 'v': goto yy150;
		default: goto yy25;
	}
yy109:
	yych = *++p;
	switch (yych) {
		case 'd': goto yy151;
		default: goto yy25;
	}
yy110:
	yych = *++p;
	switch (yych) {
		case 'g': goto yy152;
		default: goto yy25;
	}
yy111:
	yych = *++p;
	switch (yych) {
		case 'l': goto yy153;
		default: goto yy25;
	}
yy112:
	yych = *++p;
	switch (yych) {
		case 'e': goto yy154;
		default: goto yy25;
	}
yy113:
	yych = *++p;
	switch (yych) {
		case '~': goto yy155;
		default: goto yy25;
	}
yy114:
	++p;
#line 173 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1309 "block_scanner_gen.h"
yy115:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy156;
yy116:
	++p;
#line 174 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1318 "block_scanner_gen.h"
yy117:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy158;
yy118:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy160;
		default: goto yy25;
	}
yy119:
	++p;
#line 153 "block_scanner.re"
	{ return AQ_BT_LIST_UNORD; }
#line 1335 "block_scanner_gen.h"
yy120:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy161;
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy162;
		default: goto yy25;
	}
yy121:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy163;
		case '+': goto yy164;
		default: goto yy25;
	}
yy122:
	++p;
#line 152 "block_scanner.re"
	{ return AQ_BT_LIST_UNORD; }
#line 1356 "block_scanner_gen.h"
yy123:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy165;
		case '-': goto yy166;
		default: goto yy25;
	}
yy124:
	++p;
#line 144 "block_scanner.re"
	{ return AQ_BT_LIST_ORD; }
#line 1368 "block_scanner_gen.h"
yy125:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy167;
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy168;
		default: goto yy25;
	}
yy126:
	++p;
#line 71 "block_scanner.re"
	{ return AQ_BT_COMMENT; }
#line 1382 "block_scanner_gen.h"
yy127:
	yych = *++p;
	if (yych <= 0x00) goto yy169;
	goto yy25;
yy128:
	yych = *++p;
	if (yych <= 0x00) goto yy170;
	goto yy128;
yy129:
	++p;
#line 79 "block_scanner.re"
	{
        return AQ_BT_ATTR_ENTRY;
    }
#line 1397 "block_scanner_gen.h"
yy130:
	yych = *++p;
	if (yych <= 0x00) goto yy129;
	goto yy130;
yy131:
	yych = *++p;
	if (yych <= 0x00) goto yy171;
	goto yy131;
yy132:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy89;
		case '\t':
		case ' ': goto yy90;
		case ':': goto yy72;
		default: goto yy25;
	}
yy133:
	yych = *++p;
	if (yych <= 0x00) goto yy172;
	goto yy133;
yy134:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case '\t':
		case ' ': goto yy134;
		default: goto yy173;
	}
yy135:
	++p;
#line 63 "block_scanner.re"
	{ return AQ_BT_PAGE_BREAK; }
#line 1431 "block_scanner_gen.h"
yy136:
	++p;
#line 84 "block_scanner.re"
	{ return AQ_BT_SECTION_TITLE; }
#line 1436 "block_scanner_gen.h"
yy137:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy174;
		case '\t':
		case ' ': goto yy54;
		case '=': goto yy175;
		default: goto yy25;
	}
yy138:
	yych = *++p;
	if (yych <= 0x00) goto yy176;
	goto yy138;
yy139:
	yych = *++p;
	if (yych <= 0x00) goto yy177;
	goto yy139;
yy140:
	++p;
#line 130 "block_scanner.re"
	{ return AQ_BT_BLOCK_ATTR; }
#line 1458 "block_scanner_gen.h"
yy141:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy179;
yy142:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy182;
yy143:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy185;
		case ';': goto yy144;
		case ']': goto yy145;
		default: goto yy103;
	}
yy144:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy143;
		case ';': goto yy186;
		case ']': goto yy145;
		default: goto yy103;
	}
yy145:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy143;
		case ';': goto yy144;
		case ']': goto yy187;
		default: goto yy103;
	}
yy146:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy188;
		case '_': goto yy189;
		default: goto yy25;
	}
yy147:
	yych = *++p;
	switch (yych) {
		case 'o': goto yy190;
		default: goto yy25;
	}
yy148:
	yych = *++p;
	switch (yych) {
		case 'f': goto yy191;
		default: goto yy25;
	}
yy149:
	yych = *++p;
	switch (yych) {
		case 'f': goto yy192;
		default: goto yy25;
	}
yy150:
	yych = *++p;
	switch (yych) {
		case 'a': goto yy193;
		default: goto yy25;
	}
yy151:
	yych = *++p;
	switch (yych) {
		case 'e': goto yy194;
		default: goto yy25;
	}
yy152:
	yych = *++p;
	switch (yych) {
		case 'e': goto yy195;
		default: goto yy25;
	}
yy153:
	yych = *++p;
	switch (yych) {
		case 'u': goto yy196;
		default: goto yy25;
	}
yy154:
	yych = *++p;
	switch (yych) {
		case 'o': goto yy197;
		default: goto yy25;
	}
yy155:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy198;
		case ':': goto yy27;
		case ';': goto yy28;
		case '~': goto yy155;
		default: goto yy24;
	}
yy156:
	yych = *++p;
	if (yych <= 0x00) goto yy114;
	goto yy156;
yy157:
	yych = *++p;
yy158:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy159;
		default: goto yy157;
	}
yy159:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy199;
		default: goto yy157;
	}
yy160:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy200;
		default: goto yy25;
	}
yy161:
	++p;
#line 110 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1589 "block_scanner_gen.h"
yy162:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy201;
		case '\t':
		case ' ': goto yy37;
		case '*': goto yy202;
		default: goto yy25;
	}
yy163:
	++p;
#line 111 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1603 "block_scanner_gen.h"
yy164:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy203;
		case '+': goto yy164;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy165:
	++p;
#line 106 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1617 "block_scanner_gen.h"
yy166:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy204;
		case '-': goto yy166;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy167:
	++p;
#line 107 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1631 "block_scanner_gen.h"
yy168:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy205;
		case '\t':
		case ' ': goto yy43;
		case '.': goto yy168;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy169:
	++p;
#line 66 "block_scanner.re"
	{ return AQ_BT_BLOCK_COMMENT; }
#line 1647 "block_scanner_gen.h"
yy170:
	++p;
#line 146 "block_scanner.re"
	{ return AQ_BT_LIST_ORD; }
#line 1652 "block_scanner_gen.h"
yy171:
	++p;
#line 167 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1657 "block_scanner_gen.h"
yy172:
	++p;
#line 169 "block_scanner.re"
	{ return AQ_BT_LIST_DESCRIPT; }
#line 1662 "block_scanner_gen.h"
yy173:
	yych = *++p;
	if (yych <= 0x00) goto yy206;
	goto yy173;
yy174:
	++p;
#line 108 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1671 "block_scanner_gen.h"
yy175:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy207;
		case '\t':
		case ' ': goto yy54;
		case '=': goto yy208;
		default: goto yy25;
	}
yy176:
	++p;
#line 148 "block_scanner.re"
	{ return AQ_BT_LIST_ORD; }
#line 1685 "block_scanner_gen.h"
yy177:
	++p;
#line 150 "block_scanner.re"
	{ return AQ_BT_LIST_ORD; }
#line 1690 "block_scanner_gen.h"
yy178:
	yych = *++p;
yy179:
	switch (yych) {
		case 0x00: goto yy114;
		case ']': goto yy180;
		default: goto yy178;
	}
yy180:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy140;
		case ']': goto yy180;
		default: goto yy178;
	}
yy181:
	yych = *++p;
yy182:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy183;
		case ']': goto yy184;
		default: goto yy181;
	}
yy183:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy209;
		case ']': goto yy184;
		default: goto yy181;
	}
yy184:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy140;
		case ':': goto yy183;
		case ']': goto yy184;
		default: goto yy181;
	}
yy185:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy210;
		case ':': goto yy185;
		case ';': goto yy144;
		case ']': goto yy145;
		default: goto yy103;
	}
yy186:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy211;
		case ':': goto yy143;
		case ';': goto yy186;
		case ']': goto yy145;
		default: goto yy103;
	}
yy187:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy212;
		case ':': goto yy143;
		case ';': goto yy144;
		case ']': goto yy187;
		default: goto yy103;
	}
yy188:
	++p;
#line 109 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1766 "block_scanner_gen.h"
yy189:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy213;
		case ':': goto yy27;
		case ';': goto yy28;
		case '_': goto yy189;
		default: goto yy24;
	}
yy190:
	yych = *++p;
	switch (yych) {
		case ':': goto yy214;
		default: goto yy25;
	}
yy191:
	yych = *++p;
	switch (yych) {
		case ':': goto yy215;
		default: goto yy25;
	}
yy192:
	yych = *++p;
	switch (yych) {
		case ':': goto yy216;
		default: goto yy25;
	}
yy193:
	yych = *++p;
	switch (yych) {
		case 'l': goto yy217;
		default: goto yy25;
	}
yy194:
	yych = *++p;
	switch (yych) {
		case 'f': goto yy218;
		default: goto yy25;
	}
yy195:
	yych = *++p;
	switch (yych) {
		case ':': goto yy219;
		default: goto yy25;
	}
yy196:
	yych = *++p;
	switch (yych) {
		case 'd': goto yy220;
		default: goto yy25;
	}
yy197:
	yych = *++p;
	switch (yych) {
		case ':': goto yy221;
		default: goto yy25;
	}
yy198:
	++p;
#line 122 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1828 "block_scanner_gen.h"
yy199:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy222;
		case ':': goto yy199;
		default: goto yy157;
	}
yy200:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy37;
		default: goto yy25;
	}
yy201:
	++p;
#line 120 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1849 "block_scanner_gen.h"
yy202:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy201;
		case '*': goto yy202;
		case ':': goto yy27;
		case ';': goto yy28;
		default: goto yy24;
	}
yy203:
	++p;
#line 121 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1863 "block_scanner_gen.h"
yy204:
	++p;
#line 116 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1868 "block_scanner_gen.h"
yy205:
	++p;
#line 117 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1873 "block_scanner_gen.h"
yy206:
	++p;
#line 140 "block_scanner.re"
	{ return AQ_BT_LIST_CALLOUT; }
#line 1878 "block_scanner_gen.h"
yy207:
	++p;
#line 118 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1883 "block_scanner_gen.h"
yy208:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy207;
		case '\t':
		case ' ': goto yy54;
		case '=': goto yy223;
		default: goto yy25;
	}
yy209:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy224;
		case ':': goto yy209;
		case ']': goto yy184;
		default: goto yy181;
	}
yy210:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy226;
yy211:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy229;
yy212:
	++p;
#line 125 "block_scanner.re"
	{ return AQ_BT_BLOCK_ANCHOR; }
#line 1915 "block_scanner_gen.h"
yy213:
	++p;
#line 119 "block_scanner.re"
	{ return AQ_BT_DELIMITER; }
#line 1920 "block_scanner_gen.h"
yy214:
	yych = *++p;
	switch (yych) {
		case ':': goto yy232;
		default: goto yy25;
	}
yy215:
	yych = *++p;
	switch (yych) {
		case ':': goto yy233;
		default: goto yy25;
	}
yy216:
	yych = *++p;
	switch (yych) {
		case ':': goto yy234;
		default: goto yy25;
	}
yy217:
	yych = *++p;
	switch (yych) {
		case ':': goto yy235;
		default: goto yy25;
	}
yy218:
	yych = *++p;
	switch (yych) {
		case ':': goto yy236;
		default: goto yy25;
	}
yy219:
	yych = *++p;
	switch (yych) {
		case ':': goto yy237;
		default: goto yy25;
	}
yy220:
	yych = *++p;
	switch (yych) {
		case 'e': goto yy238;
		default: goto yy25;
	}
yy221:
	yych = *++p;
	switch (yych) {
		case ':': goto yy239;
		default: goto yy25;
	}
yy222:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy156;
yy223:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy207;
		case ':': goto yy27;
		case ';': goto yy28;
		case '=': goto yy223;
		default: goto yy24;
	}
yy224:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy179;
yy225:
	yych = *++p;
yy226:
	switch (yych) {
		case 0x00: goto yy114;
		case ']': goto yy227;
		default: goto yy225;
	}
yy227:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case ']': goto yy240;
		default: goto yy225;
	}
yy228:
	yych = *++p;
yy229:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy230;
		case ']': goto yy231;
		default: goto yy228;
	}
yy230:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy241;
		case ']': goto yy231;
		default: goto yy228;
	}
yy231:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy230;
		case ']': goto yy242;
		default: goto yy228;
	}
yy232:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy115;
		case '[': goto yy243;
		default: goto yy245;
	}
yy233:
	yych = *++p;
	if (yych <= 0x00) goto yy247;
	goto yy233;
yy234:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy115;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy248;
		case ':': goto yy72;
		default: goto yy25;
	}
yy235:
	yych = *++p;
	switch (yych) {
		case ':': goto yy249;
		default: goto yy25;
	}
yy236:
	yych = *++p;
	switch (yych) {
		case ':': goto yy250;
		default: goto yy25;
	}
yy237:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy115;
		case '[': goto yy251;
		default: goto yy253;
	}
yy238:
	yych = *++p;
	switch (yych) {
		case ':': goto yy255;
		default: goto yy25;
	}
yy239:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy115;
		case '[': goto yy256;
		default: goto yy258;
	}
yy240:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy212;
		case ']': goto yy240;
		default: goto yy225;
	}
yy241:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy260;
		case ':': goto yy241;
		case ']': goto yy231;
		default: goto yy228;
	}
yy242:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy212;
		case ':': goto yy230;
		case ']': goto yy242;
		default: goto yy228;
	}
yy243:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy261;
		case ';': goto yy246;
		case '[': goto yy262;
		default: goto yy243;
	}
yy244:
	yych = *++p;
yy245:
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy263;
		case ':': goto yy244;
		case ';': goto yy246;
		case '[': goto yy262;
		default: goto yy243;
	}
yy246:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy261;
		case ';': goto yy264;
		case '[': goto yy262;
		default: goto yy243;
	}
yy247:
	++p;
#line 97 "block_scanner.re"
	{ return AQ_BT_ENDIF;  }
#line 2203 "block_scanner_gen.h"
yy248:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy265;
		case ';': goto yy266;
		case '[': goto yy267;
		default: goto yy248;
	}
yy249:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy115;
		case ':': goto yy72;
		case '[': goto yy268;
		default: goto yy25;
	}
yy250:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy115;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy269;
		case ':': goto yy72;
		default: goto yy25;
	}
yy251:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy270;
		case ';': goto yy254;
		case '[': goto yy271;
		default: goto yy251;
	}
yy252:
	yych = *++p;
yy253:
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy272;
		case ':': goto yy252;
		case ';': goto yy254;
		case '[': goto yy271;
		default: goto yy251;
	}
yy254:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy270;
		case ';': goto yy273;
		case '[': goto yy271;
		default: goto yy251;
	}
yy255:
	yych = *++p;
	switch (yych) {
		case ':': goto yy274;
		default: goto yy25;
	}
yy256:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy275;
		case ';': goto yy259;
		case '[': goto yy276;
		default: goto yy256;
	}
yy257:
	yych = *++p;
yy258:
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy277;
		case ':': goto yy257;
		case ';': goto yy259;
		case '[': goto yy276;
		default: goto yy256;
	}
yy259:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy275;
		case ';': goto yy278;
		case '[': goto yy276;
		default: goto yy256;
	}
yy260:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy226;
yy261:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy244;
		case ';': goto yy246;
		case '[': goto yy262;
		default: goto yy243;
	}
yy262:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy279;
		case ';': goto yy280;
		case ']': goto yy281;
		default: goto yy262;
	}
yy263:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy283;
yy264:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy286;
		case ':': goto yy261;
		case ';': goto yy264;
		case '[': goto yy262;
		default: goto yy243;
	}
yy265:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy287;
		case ';': goto yy266;
		case '[': goto yy267;
		default: goto yy248;
	}
yy266:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy265;
		case ';': goto yy288;
		case '[': goto yy267;
		default: goto yy248;
	}
yy267:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy289;
		case ';': goto yy290;
		case ']': goto yy291;
		default: goto yy267;
	}
yy268:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy292;
		case ';': goto yy293;
		case ']': goto yy294;
		default: goto yy268;
	}
yy269:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy295;
		case ';': goto yy296;
		case '[': goto yy297;
		default: goto yy269;
	}
yy270:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy252;
		case ';': goto yy254;
		case '[': goto yy271;
		default: goto yy251;
	}
yy271:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy298;
		case ';': goto yy299;
		case ']': goto yy300;
		default: goto yy271;
	}
yy272:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy302;
yy273:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy305;
		case ':': goto yy270;
		case ';': goto yy273;
		case '[': goto yy271;
		default: goto yy251;
	}
yy274:
	yych = *++p;
	switch (yych) {
		case '\t':
		case ' ': goto yy115;
		case '[': goto yy306;
		default: goto yy308;
	}
yy275:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy257;
		case ';': goto yy259;
		case '[': goto yy276;
		default: goto yy256;
	}
yy276:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy310;
		case ';': goto yy311;
		case ']': goto yy312;
		default: goto yy276;
	}
yy277:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy314;
yy278:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy317;
		case ':': goto yy275;
		case ';': goto yy278;
		case '[': goto yy276;
		default: goto yy256;
	}
yy279:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy318;
		case ';': goto yy280;
		case ']': goto yy281;
		default: goto yy262;
	}
yy280:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy279;
		case ';': goto yy319;
		case ']': goto yy281;
		default: goto yy262;
	}
yy281:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy320;
		case ':': goto yy279;
		case ';': goto yy280;
		case ']': goto yy281;
		default: goto yy262;
	}
yy282:
	yych = *++p;
yy283:
	switch (yych) {
		case 0x00: goto yy114;
		case '[': goto yy284;
		default: goto yy282;
	}
yy284:
	yych = *++p;
yy285:
	switch (yych) {
		case 0x00: goto yy114;
		case ']': goto yy321;
		default: goto yy284;
	}
yy286:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy323;
yy287:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy327;
		case ':': goto yy287;
		case ';': goto yy266;
		case '[': goto yy267;
		default: goto yy248;
	}
yy288:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy328;
		case ':': goto yy265;
		case ';': goto yy288;
		case '[': goto yy267;
		default: goto yy248;
	}
yy289:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy329;
		case ';': goto yy290;
		case ']': goto yy291;
		default: goto yy267;
	}
yy290:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy289;
		case ';': goto yy330;
		case ']': goto yy291;
		default: goto yy267;
	}
yy291:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy331;
		case ':': goto yy289;
		case ';': goto yy290;
		case ']': goto yy291;
		default: goto yy267;
	}
yy292:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy332;
		case ';': goto yy293;
		case ']': goto yy294;
		default: goto yy268;
	}
yy293:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy292;
		case ';': goto yy333;
		case ']': goto yy294;
		default: goto yy268;
	}
yy294:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy334;
		case ':': goto yy292;
		case ';': goto yy293;
		case ']': goto yy294;
		default: goto yy268;
	}
yy295:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy335;
		case ';': goto yy296;
		case '[': goto yy297;
		default: goto yy269;
	}
yy296:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy295;
		case ';': goto yy336;
		case '[': goto yy297;
		default: goto yy269;
	}
yy297:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy337;
		case ';': goto yy338;
		case ']': goto yy339;
		default: goto yy297;
	}
yy298:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy340;
		case ';': goto yy299;
		case ']': goto yy300;
		default: goto yy271;
	}
yy299:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy298;
		case ';': goto yy341;
		case ']': goto yy300;
		default: goto yy271;
	}
yy300:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy342;
		case ':': goto yy298;
		case ';': goto yy299;
		case ']': goto yy300;
		default: goto yy271;
	}
yy301:
	yych = *++p;
yy302:
	switch (yych) {
		case 0x00: goto yy114;
		case '[': goto yy303;
		default: goto yy301;
	}
yy303:
	yych = *++p;
yy304:
	switch (yych) {
		case 0x00: goto yy114;
		case ']': goto yy343;
		default: goto yy303;
	}
yy305:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy345;
yy306:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy349;
		case ';': goto yy309;
		case '[': goto yy350;
		default: goto yy306;
	}
yy307:
	yych = *++p;
yy308:
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy351;
		case ':': goto yy307;
		case ';': goto yy309;
		case '[': goto yy350;
		default: goto yy306;
	}
yy309:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy349;
		case ';': goto yy352;
		case '[': goto yy350;
		default: goto yy306;
	}
yy310:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy353;
		case ';': goto yy311;
		case ']': goto yy312;
		default: goto yy276;
	}
yy311:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy310;
		case ';': goto yy354;
		case ']': goto yy312;
		default: goto yy276;
	}
yy312:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy355;
		case ':': goto yy310;
		case ';': goto yy311;
		case ']': goto yy312;
		default: goto yy276;
	}
yy313:
	yych = *++p;
yy314:
	switch (yych) {
		case 0x00: goto yy114;
		case '[': goto yy315;
		default: goto yy313;
	}
yy315:
	yych = *++p;
yy316:
	switch (yych) {
		case 0x00: goto yy114;
		case ']': goto yy356;
		default: goto yy315;
	}
yy317:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy358;
yy318:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy362;
		case ':': goto yy318;
		case ';': goto yy280;
		case ']': goto yy281;
		default: goto yy262;
	}
yy319:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy363;
		case ':': goto yy279;
		case ';': goto yy319;
		case ']': goto yy281;
		default: goto yy262;
	}
yy320:
	++p;
#line 91 "block_scanner.re"
	{ return AQ_BT_BLOCK_MEDIA; }
#line 2817 "block_scanner_gen.h"
yy321:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy320;
		case ']': goto yy321;
		default: goto yy284;
	}
yy322:
	yych = *++p;
yy323:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy324;
		case '[': goto yy325;
		default: goto yy322;
	}
yy324:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy364;
		case '[': goto yy325;
		default: goto yy322;
	}
yy325:
	yych = *++p;
yy326:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy365;
		case ']': goto yy366;
		default: goto yy325;
	}
yy327:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy368;
yy328:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy372;
yy329:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy376;
		case ':': goto yy329;
		case ';': goto yy290;
		case ']': goto yy291;
		default: goto yy267;
	}
yy330:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy377;
		case ':': goto yy289;
		case ';': goto yy330;
		case ']': goto yy291;
		default: goto yy267;
	}
yy331:
	++p;
#line 94 "block_scanner.re"
	{ return AQ_BT_IFDEF;  }
#line 2885 "block_scanner_gen.h"
yy332:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy378;
		case ':': goto yy332;
		case ';': goto yy293;
		case ']': goto yy294;
		default: goto yy268;
	}
yy333:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy379;
		case ':': goto yy292;
		case ';': goto yy333;
		case ']': goto yy294;
		default: goto yy268;
	}
yy334:
	++p;
#line 96 "block_scanner.re"
	{ return AQ_BT_IFEVAL; }
#line 2912 "block_scanner_gen.h"
yy335:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy380;
		case ':': goto yy335;
		case ';': goto yy296;
		case '[': goto yy297;
		default: goto yy269;
	}
yy336:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy381;
		case ':': goto yy295;
		case ';': goto yy336;
		case '[': goto yy297;
		default: goto yy269;
	}
yy337:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy382;
		case ';': goto yy338;
		case ']': goto yy339;
		default: goto yy297;
	}
yy338:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy337;
		case ';': goto yy383;
		case ']': goto yy339;
		default: goto yy297;
	}
yy339:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy384;
		case ':': goto yy337;
		case ';': goto yy338;
		case ']': goto yy339;
		default: goto yy297;
	}
yy340:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy385;
		case ':': goto yy340;
		case ';': goto yy299;
		case ']': goto yy300;
		default: goto yy271;
	}
yy341:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy386;
		case ':': goto yy298;
		case ';': goto yy341;
		case ']': goto yy300;
		default: goto yy271;
	}
yy342:
	++p;
#line 87 "block_scanner.re"
	{ return AQ_BT_BLOCK_IMAGE; }
#line 2988 "block_scanner_gen.h"
yy343:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy342;
		case ']': goto yy343;
		default: goto yy303;
	}
yy344:
	yych = *++p;
yy345:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy346;
		case '[': goto yy347;
		default: goto yy344;
	}
yy346:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy387;
		case '[': goto yy347;
		default: goto yy344;
	}
yy347:
	yych = *++p;
yy348:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy388;
		case ']': goto yy389;
		default: goto yy347;
	}
yy349:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy307;
		case ';': goto yy309;
		case '[': goto yy350;
		default: goto yy306;
	}
yy350:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy390;
		case ';': goto yy391;
		case ']': goto yy392;
		default: goto yy350;
	}
yy351:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy394;
yy352:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy397;
		case ':': goto yy349;
		case ';': goto yy352;
		case '[': goto yy350;
		default: goto yy306;
	}
yy353:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy398;
		case ':': goto yy353;
		case ';': goto yy311;
		case ']': goto yy312;
		default: goto yy276;
	}
yy354:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy399;
		case ':': goto yy310;
		case ';': goto yy354;
		case ']': goto yy312;
		default: goto yy276;
	}
yy355:
	++p;
#line 90 "block_scanner.re"
	{ return AQ_BT_BLOCK_MEDIA; }
#line 3081 "block_scanner_gen.h"
yy356:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy355;
		case ']': goto yy356;
		default: goto yy315;
	}
yy357:
	yych = *++p;
yy358:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy359;
		case '[': goto yy360;
		default: goto yy357;
	}
yy359:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy400;
		case '[': goto yy360;
		default: goto yy357;
	}
yy360:
	yych = *++p;
yy361:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy401;
		case ']': goto yy402;
		default: goto yy360;
	}
yy362:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy285;
yy363:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy326;
yy364:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy403;
		case ':': goto yy364;
		case '[': goto yy325;
		default: goto yy322;
	}
yy365:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy404;
		case ']': goto yy366;
		default: goto yy325;
	}
yy366:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy320;
		case ':': goto yy365;
		case ']': goto yy366;
		default: goto yy325;
	}
yy367:
	yych = *++p;
yy368:
	switch (yych) {
		case 0x00: goto yy114;
		case '[': goto yy369;
		default: goto yy367;
	}
yy369:
	yych = *++p;
yy370:
	switch (yych) {
		case 0x00: goto yy114;
		case ']': goto yy405;
		default: goto yy369;
	}
yy371:
	yych = *++p;
yy372:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy373;
		case '[': goto yy374;
		default: goto yy371;
	}
yy373:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy406;
		case '[': goto yy374;
		default: goto yy371;
	}
yy374:
	yych = *++p;
yy375:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy407;
		case ']': goto yy408;
		default: goto yy374;
	}
yy376:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy370;
yy377:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy375;
yy378:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy410;
yy379:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy413;
yy380:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy417;
yy381:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy421;
yy382:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy425;
		case ':': goto yy382;
		case ';': goto yy338;
		case ']': goto yy339;
		default: goto yy297;
	}
yy383:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy426;
		case ':': goto yy337;
		case ';': goto yy383;
		case ']': goto yy339;
		default: goto yy297;
	}
yy384:
	++p;
#line 95 "block_scanner.re"
	{ return AQ_BT_IFNDEF; }
#line 3241 "block_scanner_gen.h"
yy385:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy304;
yy386:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy348;
yy387:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy427;
		case ':': goto yy387;
		case '[': goto yy347;
		default: goto yy344;
	}
yy388:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy428;
		case ']': goto yy389;
		default: goto yy347;
	}
yy389:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy342;
		case ':': goto yy388;
		case ']': goto yy389;
		default: goto yy347;
	}
yy390:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy429;
		case ';': goto yy391;
		case ']': goto yy392;
		default: goto yy350;
	}
yy391:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy26;
		case ':': goto yy390;
		case ';': goto yy430;
		case ']': goto yy392;
		default: goto yy350;
	}
yy392:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy431;
		case ':': goto yy390;
		case ';': goto yy391;
		case ']': goto yy392;
		default: goto yy350;
	}
yy393:
	yych = *++p;
yy394:
	switch (yych) {
		case 0x00: goto yy114;
		case '[': goto yy395;
		default: goto yy393;
	}
yy395:
	yych = *++p;
yy396:
	switch (yych) {
		case 0x00: goto yy114;
		case ']': goto yy432;
		default: goto yy395;
	}
yy397:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy434;
yy398:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy316;
yy399:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy361;
yy400:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy438;
		case ':': goto yy400;
		case '[': goto yy360;
		default: goto yy357;
	}
yy401:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy439;
		case ']': goto yy402;
		default: goto yy360;
	}
yy402:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy355;
		case ':': goto yy401;
		case ']': goto yy402;
		default: goto yy360;
	}
yy403:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy283;
yy404:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy440;
		case ':': goto yy404;
		case ']': goto yy366;
		default: goto yy325;
	}
yy405:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy331;
		case ']': goto yy405;
		default: goto yy369;
	}
yy406:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy441;
		case ':': goto yy406;
		case '[': goto yy374;
		default: goto yy371;
	}
yy407:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy442;
		case ']': goto yy408;
		default: goto yy374;
	}
yy408:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy331;
		case ':': goto yy407;
		case ']': goto yy408;
		default: goto yy374;
	}
yy409:
	yych = *++p;
yy410:
	switch (yych) {
		case 0x00: goto yy114;
		case ']': goto yy411;
		default: goto yy409;
	}
yy411:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy334;
		case ']': goto yy411;
		default: goto yy409;
	}
yy412:
	yych = *++p;
yy413:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy414;
		case ']': goto yy415;
		default: goto yy412;
	}
yy414:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy443;
		case ']': goto yy415;
		default: goto yy412;
	}
yy415:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy334;
		case ':': goto yy414;
		case ']': goto yy415;
		default: goto yy412;
	}
yy416:
	yych = *++p;
yy417:
	switch (yych) {
		case 0x00: goto yy114;
		case '[': goto yy418;
		default: goto yy416;
	}
yy418:
	yych = *++p;
yy419:
	switch (yych) {
		case 0x00: goto yy114;
		case ']': goto yy444;
		default: goto yy418;
	}
yy420:
	yych = *++p;
yy421:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy422;
		case '[': goto yy423;
		default: goto yy420;
	}
yy422:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy445;
		case '[': goto yy423;
		default: goto yy420;
	}
yy423:
	yych = *++p;
yy424:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy446;
		case ']': goto yy447;
		default: goto yy423;
	}
yy425:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy419;
yy426:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy424;
yy427:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy302;
yy428:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy448;
		case ':': goto yy428;
		case ']': goto yy389;
		default: goto yy347;
	}
yy429:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy449;
		case ':': goto yy429;
		case ';': goto yy391;
		case ']': goto yy392;
		default: goto yy350;
	}
yy430:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case '\t':
		case ' ': goto yy450;
		case ':': goto yy390;
		case ';': goto yy430;
		case ']': goto yy392;
		default: goto yy350;
	}
yy431:
	++p;
#line 100 "block_scanner.re"
	{ return AQ_BT_INCLUDE; }
#line 3534 "block_scanner_gen.h"
yy432:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy431;
		case ']': goto yy432;
		default: goto yy395;
	}
yy433:
	yych = *++p;
yy434:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy435;
		case '[': goto yy436;
		default: goto yy433;
	}
yy435:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy451;
		case '[': goto yy436;
		default: goto yy433;
	}
yy436:
	yych = *++p;
yy437:
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy452;
		case ']': goto yy453;
		default: goto yy436;
	}
yy438:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy314;
yy439:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy454;
		case ':': goto yy439;
		case ']': goto yy402;
		default: goto yy360;
	}
yy440:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy285;
yy441:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy368;
yy442:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy455;
		case ':': goto yy442;
		case ']': goto yy408;
		default: goto yy374;
	}
yy443:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy456;
		case ':': goto yy443;
		case ']': goto yy415;
		default: goto yy412;
	}
yy444:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy384;
		case ']': goto yy444;
		default: goto yy418;
	}
yy445:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy457;
		case ':': goto yy445;
		case '[': goto yy423;
		default: goto yy420;
	}
yy446:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy458;
		case ']': goto yy447;
		default: goto yy423;
	}
yy447:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy384;
		case ':': goto yy446;
		case ']': goto yy447;
		default: goto yy423;
	}
yy448:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy304;
yy449:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy396;
yy450:
	yych = *++p;
	if (yych <= 0x00) goto yy26;
	goto yy437;
yy451:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy459;
		case ':': goto yy451;
		case '[': goto yy436;
		default: goto yy433;
	}
yy452:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy116;
		case ':': goto yy460;
		case ']': goto yy453;
		default: goto yy436;
	}
yy453:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy431;
		case ':': goto yy452;
		case ']': goto yy453;
		default: goto yy436;
	}
yy454:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy316;
yy455:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy370;
yy456:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy410;
yy457:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy417;
yy458:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy461;
		case ':': goto yy458;
		case ']': goto yy447;
		default: goto yy423;
	}
yy459:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy394;
yy460:
	yych = *++p;
	switch (yych) {
		case 0x00: goto yy114;
		case '\t':
		case ' ': goto yy462;
		case ':': goto yy460;
		case ']': goto yy453;
		default: goto yy436;
	}
yy461:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy419;
yy462:
	yych = *++p;
	if (yych <= 0x00) goto yy116;
	goto yy396;
}
#line 179 "block_scanner.re"

}
